### ISSUE TITLE
Documentation update checklist

### ISSUE THREAD

**Issue by cristinavn** [Arquisoft/InciDashboard_i3a#55]
## DOCUMENT
- [x] A001 All the   sections inside the documentation template are compulsory. None of them can   be deleted. If any section is not applicable, fill it with "N/A"

- [x] A002 Bear   in mind that you have to integrate the given document with the final   architecture: your architecture and the architecture of the other team, all   together in one only final document. Therefore, you have to take under   control version control, references, styles, etc. in order to not to spend   much time during the integration.

- [x] A003 Columns   of every table into the document are compulsory and cannot be deleted.   Template format have to be followed to guaranty information traceability.

- [x] A004 The   document must be numbered according to the standard UNE-50132:1994

- [x] A005 Final   deliverable have to be in PDF formatand must contain a lateral table of   contents (Bookmark panel)

- [x] A006 Put   the authors' name. So in the authors page as in the footer

- [x] A007 Be   sure that your team deliver the correct version of the document.
##  GENERAL
- [x] B001 It   is a big error misunderstanding analysis/design and software architecture. It   is even worse to create a context view based on classes. This could be a   cause for the practice work not to be passed.

- [x] B002 The   document describing the architecture must be complete. If there are missing   parts or some views has been left incomplete, it is reason enought for the   practice work not to be passed.
##  STAKEHOLDERS

- [x] C001 Identify stakeholders really related to the application.

- [x] C002 Both teams are different stakeholders during all the practice work. Even after   integration.
##  QUALITY   ATTRIBUTES

- [x] D001 Every quality attribute will have a code. It is not necessary for the quality   attributes to be ordered, add them at the bottom of the current list. Avoid   changing codes of existing attributes.

- [x] D002 If a quality attributeis deleted, its code and entry in the QA table mus be   reserved, it data deleted and only the label "DELETED" added into   the QA description.

- [x] D003 Do not forget the quality attributes related to usability and accessibility. A   public portal in Spain have to be AA of W3C.

- [x] D004 Add constrains (OT & OC) to the table of the section 9 (Views). All the   Quality attributes (AT), Organizations Constrains (OC) and Techniligical   Constrain (TC) must be in this table.

- [x] D005 Quality attributes have to represent NON-FUNCTIONAL requirements. Never they comes   from FUNCTIONAL requirements. Delete from the table every QA which represent   a functional requirement.
## SCENARIOS

- [x] E001 There must be enough quality scenarios as for cover each quality attribute. Each   quality attribute can be referenced in more than one scenario and one   scenario can refer to more than one quality attribute.

- [x] E002 In general, if a scenario covers more than one QA, and any of these QA does not   appear in other different scenario, it is very probable that the architecture   was not complette.

- [x] E003 Remember that quality scenarios have to be tested by means of the “measure of   response”, so this field have to contain something that can be measurable.

- [x] E004 Add scenarios for constrains. If they result to be obvious, simple write   "OBVIOUS SCENARIO". In any case keep this scenario entry in the   table because of academic reasons.
## VIEWS

- [x] F001 Do not confuse the context for the stakeholders (section 7) with the formal   context view (section 9.1). All references in this checklist to the context   view refer to the one in section 9.1

- [x] F002  Avoid   creating more than one context view. By using the SEI methodology, the   architecture design starts on the complete system that is being broken into   subsystems and components in each iteration. The final views structure is a   tree, in which the root node is the context view. Therefore, in a system as   simple as this one, there exist only one context view.

- [x] F003 It   is necessary to add a Rational section to the Context View

- [x] F004 Context   diagram should have correspondence with the views which come from it. All the   interfaces of the subsystems have to appear in the corresponding views.If one   interface comes into several interfaces during an iteration to crate a deeper   level view, they have to be documented adecuately in both views.

- [x] F005 Views   must be complete, containing all the related elements. For example, context   diagram must contain all the created subsystems plus the database and the   Apache Kafka subsystem (or component).

- [x] F006 Important:   each view, even the context view, have to include a "Rationale" to   justify decisions.

- [x] F007 Each   justification must be a text in which you explain the decision adopted for   solving the requirements of a quality attribute or a scenario. this include:   braking into more deep modules, choose an interface, a module responsibility,   technological decisions, etc.

- [x] F008 Rational   section in every view must contain the reference of the attributes and   constrais that the view solves.

- [x] F009 If   the first subsystems (Loader and Agents) come togother in one, create a   system to put them inside. For example a AgentsManagement system

- [x] F010 Do   not use in the the formal views any elements that was not formal or do not   represent formal concepts (system, subsystem, components, etc.)

- [x] F011 There   must exist views enough as for every quality attribute and every scenario   have a reference in one view at least.

- [x] F012 If   a view has no scenario or quality attribute referenced, perhaps is because   this view is not necessary.

- [x] F013 I remind you the 7/9 rule. More than 7/9 elements (subsystems, components,   etc.) in a view, makes the view difficult to be understood.

- [x] F014 Very important: final document must   describe one context view, several components and connectors view (as much as   needed), on package view and one deployment view. Packages and Deployment   views are compulsory for May presentation. Moreover, the document must   contain a BPMN description of the business.
## DOCUMENT,   CODE & TRACEABILITY

- [x] G001 The document will let be traced forward and backward. Forward, from requirements   to rational, and backward, from rational to requirements. Keep the tables   that let you navigate through the document updated is extremely important.

- [x] G002 The following traceability scheme must be possible: Non-functional requirement   >> Quality attribute (s) >> Scenario (s) >> View (s)   >> Code in Java

- [x] G003 The reverse traceability mut be possible also

- [x] G004 The names chosen for the components, systems, etc. in the architecture and the   corresponding ones for the Java code MUST BE IDENTICAL to guarantee the   traceability

- [x] G005 Each element of the architecture must have its correspondence in the Java code.   Some type of technological solution--spring boots, singleton, etc.--must be   used for the systems, subsystems, components, etc. The chosen technology must   be the same for the entire complete project.

**Comment by eleallegue** [comment]
**UPDATE**
The unchecked elements are due to the Views section that is not implemented yet

**Comment by eleallegue** [comment]
**FINALLY DONE**
